### ISSUE TITLE
A Small update in tutorial link : http://chrisalbon.com/python/breaking_up_string_variables.html

### ISSUE THREAD

**Issue by megabytes1024kb** [chrisalbon/mlai#15]
http://chrisalbon.com/python/breaking_up_string_variables.html
In this Page link
Section : **Breaking up a number into seperate variables**

the given sentence as 
firstNumber, secondNumber, thirdNumber, fourthNumber = '9485'
print firstNumber which printed as 'B' instead of 9
and so on

**Comment by chrisalbon** [comment]
fixed!
