### ISSUE TITLE
Six seat configuration

### ISSUE THREAD

**Issue by etchen99** [chrisalbon/mlai#16]
http://chrisalbon.com/articles/aisle_seat_probabilities.html

On flights I've been on, it's broken up into 3 + 3 with a single aisle.  So two aisle seats.  I haven't seen your row6 configuration.

**Comment by cra** [comment]
In any way, the article features unrealistic setup
```python
# An aircraft with six seats per row
rows6 = [0,1,1,0,1,0, np.nan, np.nan, np.nan]
```

It feels like the ones should come in pairs for any case

**Comment by brseay** [comment]
you could just find out what equipment you're on.
and your probabilities are not weighed by the distribution of aircraft.

**Comment by chrisalbon** [comment]
@cra Good catch thanks

@brseay distribution of the aircraft?
