### ISSUE TITLE
Pandas

### ISSUE THREAD

**Issue by yeshivadan** [chrisalbon/mlai#21]
Can you do a tutorial on how to combine two columns together. E.g. column a, column b. 

The result is column a with both columns in it.

**Comment by chrisalbon** [comment]
You mean like df['col_1'] + df[col_2']?

**Comment by yeshivadan** [comment]
Like this
http://stackoverflow.com/questions/19377969/combine-two-columns-of-text-in-dataframe-in-pandas-python

Also, loading in excelfile topic, not sure what the code is, it should
pd.read_excel

You wrote pd.ExcelFile ()

**Comment by eenblam** [comment]
@yeshivadan 
> The result is column a with both columns in it.

The example you gave is equivalent to the one Chris provided, with the exception that it was necessary to call `.map(str)` on the numeric column.

> Also, loading in excelfile topic, not sure what the code is

`pd.read_excel` is a more comprehensive, single-call API for reading Excel workbooks. It immediately **returns a dataframe.**

`pd.ExcelFile()` is **the constructor for an ExcelFile object**, not a dataframe. This is how Chris is able to obtain the names of the sheets in the file (`xls_file.sheet_names`) and then load a specific one as a dataframe (`xls_file.parse('Sheet1')`). The `sheet_names` attribute seems to be the only thing you gain from using this interface, but it could be nice to have that intermediate step when processing a lot of workbooks automatically. See `help(pd.ExcelFile)`.
