### ISSUE TITLE
(typo) The Probability An Economy Seat Is An Aisle? 

### ISSUE THREAD

**Issue by 2324** [chrisalbon/mlai#22]
With this issue - I would like to bring to notice a typo as below, it shouldn't be **slights** but **flights**:
<img width="579" alt="screen shot 2016-09-13 at 9 19 23 pm" src="https://cloud.githubusercontent.com/assets/20545350/18480885/ed40e862-79f7-11e6-8434-f56a88eca264.png">

**Comment by chrisalbon** [comment]
sixed!
