### ISSUE TITLE
lmplot function in seaborn doesn't contain parameter "dropna"

### ISSUE THREAD

**Issue by olivertomic** [chrisalbon/mlai#23]
Hey Chris,

thanks a lot for the great code snippets and recipes on your web site. They saved me a lot of time finding the right syntax.

I just tested out the code for scatter plot in seaborn:
http://chrisalbon.com/python/seaborn_scatterplot.html 

It seems that the lmplot function in seaborn doesn't have the paramter "dropna" any longer and throws this error. 

TypeError: lmplot() got an unexpected keyword argument 'dropna'

Just checked the documentation and could not find any 'dropna' argument there. I guess you used an older version of seaborn when you coded the scatter plot example?

Cheers
Oliver

**Comment by chrisalbon** [comment]
fixed
