### ISSUE TITLE
Mispelled 'separate' and reused example from above. 

### ISSUE THREAD

**Issue by Moondra** [chrisalbon/mlai#31]
Hi, 
http://chrisalbon.com/python/breaking_up_string_variables.html
"Breaking up a number into seperate variables"

has the word separate misspelled. 

Also, instead of breaking up the numbers shown into separate values, under the section "Breaking up a number into seperate variables",  you are breaking up the string from the earlier example, which is a duplicate.  

Amit

**Comment by sbermancrossville** [comment]
I just noticed this too

**Comment by chrisalbon** [comment]
thanks fixed!
