### ISSUE TITLE
dropna paremeter does not exist in lmplot() function

### ISSUE THREAD

**Issue by arvinsim** [chrisalbon/mlai#38]
http://chrisalbon.com/python/seaborn_scatterplot.html

I get an error`TypeError: lmplot() got an unexpected keyword argument 'dropna'`

Looking at the [documentation](http://seaborn.pydata.org/generated/seaborn.lmplot.html), it seems that the `dropna` parameter does not exist

**Comment by chrisalbon** [comment]
fixed!
