### ISSUE TITLE
c.Notebook config missing value

### ISSUE THREAD

**Issue by nathanmargaglio** [chrisalbon/mlai#39]
In [this article](http://chrisalbon.com/jupyter/run_project_jupyter_on_amazon_ec2.html) you give us the following lines to add to the `jupyter_notebook_config.py` file:

```
c = get_config()

#Kernel config
c.IPKernelApp.pylab = 'inline'  # if you want plotting support always in your notebook

#Notebook config
c.NotebookApp.certfile = u'/home/ubuntu/certs/mycert.pem' #location of your certificate file
c.NotebookApp.ip = '*'
c.NotebookApp.open_browser = False  #so that the ipython notebook does not opens up a browser by default
c.NotebookApp.password = u'sha1:98ff0e580111:12798c72623a6eecd54b51c006b1050f0ac1a62d'  #the encrypted password we generated above
# It is a good idea to put it on a known, fixed port
c.NotebookApp.port = 8888
```

But this results in `SSLError: [SSL] PEM lib (_ssl.c:2599)` in my case.  I was able to resolve this by adding this line:
`c.NotebookApp.keyfile = u'/home/ubuntu/certs/mycert.key' #location of your key file`
to the end of the file.  I'm guessing my particular case might be the result of a mistake on my end, but in any case, I wanted to put this out there since there doesn't seem to much on the topic anywhere.

**Comment by chrisalbon** [comment]
fixed!
