### ISSUE TITLE
Viewing the site offline?

### ISSUE THREAD

**Issue by phume** [chrisalbon/mlai#45]
Hi Chris, 

First of all, thank you so much for creating this site, http://chrisalbon.com/ (Notes on Data Science, Machine Learning, & Artificial Intelligence). I always end up at your site when I googled something about pandas and R. I was wondering if you are planning to make it available offline or in pdf form?

Thanks again!!

**Comment by chrisalbon** [comment]
Hey Phume,

I didn't have any plans for that. However, if you want it offline, just download the zip of the [gh-pages repo](https://github.com/chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence/tree/gh-pages) and then you can view it offline.

**Comment by phume** [comment]
Thanks, Chris!!
