### ISSUE TITLE
Indexing and Selecting Data With Pandas - Chris Albon

### ISSUE THREAD

**Issue by bms91** [chrisalbon/mlai#46]
Referring to: http://chrisalbon.com/python/pandas_indexing_selecting.html

Dear Chris Albon,

Select rows by row number:

# Select the second and third row
df.iloc[1:2]

I think this refers only to the second row. 

Thanks and sorry if I have misunderstood.

Best,
Martin

**Comment by nablue** [comment]
Additional error:
df.iloc[2:] does not select every row **after** the third row.  Rather, it selects every row **beginning with** the third row.

**Comment by chrisalbon** [comment]
fixed thanks!
