### ISSUE TITLE
ImportError: cannot import name '_thread'

### ISSUE THREAD

**Issue by purgoufr** [chrisalbon/mlai#53]
I used the example which stay in "https://chrisalbon.com/python/beautiful_soup_scrape_table.html" .

Then I received error like this;
![1](https://cloud.githubusercontent.com/assets/12126559/24096343/f384ebe6-0d69-11e7-9ab2-11a0e65b839d.PNG)

Problem is "import pandas as pd", but I can not solve this problem. Do you any suggestion about that?

**Comment by chrisalbon** [comment]
fixed!
