### ISSUE TITLE
Code not doing what title promises

### ISSUE THREAD

**Issue by heikkil** [chrisalbon/mlai#57]
On page https://chrisalbon.com/python/matplotlib_scatterplot_from_pandas.html
the last plot seems not to have the correct code:

**Scatterplot of preTestScore and postTestScore with the size = 300 and the color determined by sex**
````
plt.scatter(df.preTestScore, df.postTestScore, s=300, c='m')
# should be
plt.scatter(df.preTestScore, df.postTestScore, s=300, c=df.female)
````

**Comment by chrisalbon** [comment]
fixed!
