### ISSUE TITLE
password value for 'Run Project Jupyter Notebooks On Amazon EC2'?

### ISSUE THREAD

**Issue by mjjohns1** [chrisalbon/mlai#58]
Followed your very handy guide for connecting a jupyter notebook to an ec2 instance and everything works great until I get to the point of the last screen shot. What password are you supposed to use to log into the notebook? Nothing i've tried works.

**Comment by evanagovino** [comment]
I just did this and ran across the same problem. I changed the password temporarily and it worked. I'm not sure if there's an issue copying and pasting a big unicode string?

**Comment by joshjacobson** [comment]
@evanagovino How did you change the password temporarily?

+1 on this issue.

**Comment by chrisalbon** [comment]
fixed!
