### ISSUE TITLE
Grammatical error in for_loop 

### ISSUE THREAD

**Issue by frieds** [chrisalbon/mlai#62]
Please see https://chrisalbon.com/python/for_loops.html

I think you can remove the words "has been". The "sequence processes" - as in ends after a certain number of steps have been taken. "Has been" indicates a past event which doesn't align with the verb "processes" since that's present tense.

Otherwise, you can leave "has been" and change "processes" to "processed" since "has been" is the past tense so the verb "process" should also be in its tense form.

**Comment by chrisalbon** [comment]
fixed thanks!
