### ISSUE TITLE
Column "ScoresBinned" in blog post "Binning Data in Pandas"?

### ISSUE THREAD

**Issue by mattiasostmar** [chrisalbon/mlai#66]
Hi! Thanks for taking the time to tutor in Pandas!

In your blog post Binning Data in Pandas on crisalbon.com there is a column "ScoresBinned" in the final DataFrame, but no explanation how it got there. It had been really nice!

I checked in [the underlying notebook](https://chrisalbon.com/python/pandas_binning_data.html), but it's not there either. I would very much appreciate if you would take the time to update the blog post - it's a very useful aspect of the flow!

Regards,
/Mattias

**Comment by maneesha** [comment]
I came across the same thing today so I submitted a PR: https://github.com/chrisalbon/notes_on_data_science_machine_learning_and_artificial_intelligence/pull/73

**Comment by chrisalbon** [comment]
Fixed!
