### ISSUE TITLE
Errors in Python Basics String Indexing

### ISSUE THREAD

**Issue by nablue** [chrisalbon/mlai#74]
Print the first three characters:
    Should be string[0:3] and string[:3], to get 'Str'
    Not string[0:2] and string[:2], which yield 'St'
Print the third to fifth characters:
    Should be string[2:5] instead of string[2:4]
Print the first to the tenth character, skipping every other character:
    string[0:10:2] would be better than string[0:9:2], which only looks at the first nine characters.

**Comment by chrisalbon** [comment]
fixed!
