### ISSUE TITLE
create_list_from_dictionary_keys_and_values

### ISSUE THREAD

**Issue by ajasja** [chrisalbon/mlai#8]
HI!

The page http://chrisalbon.com/python/create_list_from_dictionary_keys_and_values.html does not give sound advice.

Just calling `dict.keys()` and  `dict.values()` already gives the needed lists. There is absolutely no need to build it again in a loop.

**Comment by tdhopper** [comment]
In Python3, they don't give lists, but you can get them with `list(dict.keys())`, etc.
