### ISSUE TITLE
Errors in https://chrisalbon.com/python/data_structure_basics.html

### ISSUE THREAD

**Issue by nablue** [chrisalbon/mlai#80]
The code for "# Reverse sort list, then print the results", should be allies.reverse() -- not allies.sort().
The list should start with 'USA' -- not 'Australia'.
Answers to the next several examples should be changed to match the reversed list.
The final example should be titled "# What is the **intersection** of BRI and BRIC?"  -- not "# What items are the **union** of BRI and BRIC?".

**Comment by chrisalbon** [comment]
fixed!
