### ISSUE TITLE
Missing Output in https://chrisalbon.com/python/pandas_hierarchical_data.html

### ISSUE THREAD

**Issue by nablue** [chrisalbon/mlai#85]
Between the following two lines of code:
df.set_index(['regiment', 'company'], drop=False)
df
The output of the first line is omitted.  
A dataframe should be displayed with 'regiment' and 'company' each appearing twice:  once in the index and once as a column of the dataframe.  (The 'name', 'preTestScore', and 'postTestScore' columns should also be displayed.)

**Comment by chrisalbon** [comment]
fixed
