### ISSUE TITLE
Error in https://chrisalbon.com/python/geocoding_and_reverse_geocoding.html

### ISSUE THREAD

**Issue by natethedrummer** [chrisalbon/mlai#90]
Geocode sometimes returns legitimate results even when the valid_address function returns False.  

This is an open issue: https://bitbucket.org/xster/pygeocoder/issues/22/geocoderresultvalid_address-doesnt-work.

I recommend excluding the valid_address function from the tutorial.

**Comment by chrisalbon** [comment]
fixed!
